// Medal times in ms per track. Generated by `node tools/medals.mjs` from AI runs:
// author is just under the best bot lap; gold/silver/bronze are +5% / +17% / +35%.
export const MEDALS = {
  'green-start': {
    author: 75610,
    gold: 80600,
    silver: 89800,
    bronze: 103600
  },
  'rolling-hills': {
    author: 31220,
    gold: 33300,
    silver: 37100,
    bronze: 42800
  },
  'meadow-loop': {
    author: 73250,
    gold: 78100,
    silver: 87000,
    bronze: 100400
  },
  'mesa-run': {
    author: 37770,
    gold: 40300,
    silver: 44900,
    bronze: 51800
  },
  'canyon-drift': {
    author: 100880,
    gold: 107500,
    silver: 119800,
    bronze: 138300
  },
  'dune-jumper': {
    author: 36090,
    gold: 38500,
    silver: 42900,
    bronze: 49500
  },
  'glacier-pass': {
    author: 42490,
    gold: 45300,
    silver: 50500,
    bronze: 58200
  },
  summit: {
    author: 65570,
    gold: 69900,
    silver: 77900,
    bronze: 89900
  },
  'palm-beach': {
    author: 79430,
    gold: 84700,
    silver: 94300,
    bronze: 108900
  },
  'island-hopper': {
    author: 36400,
    gold: 38800,
    silver: 43200,
    bronze: 49900
  },
  'maple-mile': {
    author: 71310,
    gold: 76000,
    silver: 84700,
    bronze: 97700
  },
  'leaf-storm': {
    author: 37910,
    gold: 40400,
    silver: 45000,
    bronze: 52000
  },
  'neon-boulevard': {
    author: 96990,
    gold: 103400,
    silver: 115200,
    bronze: 132900
  },
  overdrive: {
    author: 36860,
    gold: 39300,
    silver: 43800,
    bronze: 50500
  },
  'midnight-spiral': {
    author: 64630,
    gold: 68900,
    silver: 76800,
    bronze: 88600
  },
  'magma-rush': {
    author: 36900,
    gold: 39300,
    silver: 43800,
    bronze: 50600
  },
  caldera: {
    author: 84070,
    gold: 89600,
    silver: 99900,
    bronze: 115200
  },
  stardust: {
    author: 39030,
    gold: 41600,
    silver: 46400,
    bronze: 53500
  },
  'orbit-ring': {
    author: 70320,
    gold: 75000,
    silver: 83500,
    bronze: 96400
  },
  'grand-finale': {
    author: 67780,
    gold: 72300,
    silver: 80500,
    bronze: 92900
  }
};
