// Medal times in ms per track. Generated by `node tools/medals.mjs` from AI runs:
// author is just under the best bot lap; gold/silver/bronze are +5% / +17% / +35%.
export const MEDALS = {
  'green-start': {
    author: 76100,
    gold: 81100,
    silver: 90400,
    bronze: 104300
  },
  'rolling-hills': {
    author: 31070,
    gold: 33100,
    silver: 36900,
    bronze: 42600
  },
  'meadow-loop': {
    author: 76270,
    gold: 81300,
    silver: 90600,
    bronze: 104500
  },
  'mesa-run': {
    author: 35670,
    gold: 38000,
    silver: 42400,
    bronze: 48900
  },
  'canyon-drift': {
    author: 100850,
    gold: 107500,
    silver: 119800,
    bronze: 138200
  },
  'dune-jumper': {
    author: 35350,
    gold: 37700,
    silver: 42000,
    bronze: 48400
  },
  'glacier-pass': {
    author: 41700,
    gold: 44400,
    silver: 49500,
    bronze: 57100
  },
  summit: {
    author: 65610,
    gold: 69900,
    silver: 77900,
    bronze: 89900
  },
  'palm-beach': {
    author: 79480,
    gold: 84700,
    silver: 94400,
    bronze: 108900
  },
  'island-hopper': {
    author: 38420,
    gold: 41000,
    silver: 45600,
    bronze: 52700
  },
  'maple-mile': {
    author: 71220,
    gold: 75900,
    silver: 84600,
    bronze: 97600
  },
  'leaf-storm': {
    author: 38270,
    gold: 40800,
    silver: 45500,
    bronze: 52500
  },
  'neon-boulevard': {
    author: 97640,
    gold: 104100,
    silver: 116000,
    bronze: 133800
  },
  overdrive: {
    author: 40390,
    gold: 43100,
    silver: 48000,
    bronze: 55400
  },
  'midnight-spiral': {
    author: 65420,
    gold: 69700,
    silver: 77700,
    bronze: 89700
  },
  'magma-rush': {
    author: 37230,
    gold: 39700,
    silver: 44200,
    bronze: 51000
  },
  caldera: {
    author: 83460,
    gold: 89000,
    silver: 99100,
    bronze: 114400
  },
  stardust: {
    author: 44200,
    gold: 47100,
    silver: 52500,
    bronze: 60600
  },
  'orbit-ring': {
    author: 71030,
    gold: 75700,
    silver: 84400,
    bronze: 97300
  },
  'grand-finale': {
    author: 70470,
    gold: 75100,
    silver: 83700,
    bronze: 96600
  }
};
