// Medal times in ms per track. Generated by `node tools/medals.mjs` from AI runs:
// author is just under the best bot lap; gold/silver/bronze are +5% / +17% / +35%.
export const MEDALS = {
  'green-start': {
    author: 76100,
    gold: 81100,
    silver: 90400,
    bronze: 104300
  },
  'rolling-hills': {
    author: 30740,
    gold: 32800,
    silver: 36500,
    bronze: 42100
  },
  'meadow-loop': {
    author: 76270,
    gold: 81300,
    silver: 90600,
    bronze: 104500
  },
  'mesa-run': {
    author: 38030,
    gold: 40500,
    silver: 45200,
    bronze: 52100
  },
  'canyon-drift': {
    author: 100850,
    gold: 107500,
    silver: 119800,
    bronze: 138200
  },
  'dune-jumper': {
    author: 39770,
    gold: 42400,
    silver: 47200,
    bronze: 54500
  },
  'glacier-pass': {
    author: 41820,
    gold: 44600,
    silver: 49700,
    bronze: 57300
  },
  summit: {
    author: 65610,
    gold: 69900,
    silver: 77900,
    bronze: 89900
  },
  'palm-beach': {
    author: 79480,
    gold: 84700,
    silver: 94400,
    bronze: 108900
  },
  'island-hopper': {
    author: 40440,
    gold: 43100,
    silver: 48000,
    bronze: 55400
  },
  'maple-mile': {
    author: 71220,
    gold: 75900,
    silver: 84600,
    bronze: 97600
  },
  'leaf-storm': {
    author: 38040,
    gold: 40600,
    silver: 45200,
    bronze: 52100
  },
  'neon-boulevard': {
    author: 97640,
    gold: 104100,
    silver: 116000,
    bronze: 133800
  },
  overdrive: {
    author: 40040,
    gold: 42700,
    silver: 47600,
    bronze: 54900
  },
  'midnight-spiral': {
    author: 65420,
    gold: 69700,
    silver: 77700,
    bronze: 89700
  },
  'magma-rush': {
    author: 36680,
    gold: 39100,
    silver: 43600,
    bronze: 50300
  },
  caldera: {
    author: 83460,
    gold: 89000,
    silver: 99100,
    bronze: 114400
  },
  stardust: {
    author: 44050,
    gold: 47000,
    silver: 52300,
    bronze: 60400
  },
  'orbit-ring': {
    author: 71030,
    gold: 75700,
    silver: 84400,
    bronze: 97300
  },
  'grand-finale': {
    author: 70390,
    gold: 75000,
    silver: 83600,
    bronze: 96500
  }
};
