// Generates medal times from AI runs: the bot at full skill sets the author
// time; gold/silver/bronze are fixed margins above it. Writes src/track/medals.js.
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TRACKS } from '../src/track/tracks.js';
import { simulate } from './simcore.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = {};
const round = (ms, step) => Math.round(ms / step) * step;
for (const def of TRACKS) {
  // best of a few runs with different lateral personalities
  let best = Infinity;
  for (const seed of [1, 2, 3]) {
    const r = simulate(def, { skill: 1, seed });
    if (r.finished && r.respawns === 0) best = Math.min(best, r.time);
  }
  if (!isFinite(best)) { console.log('NO CLEAN RUN', def.id); continue; }
  const ms = best * 1000;
  out[def.id] = {
    author: round(ms * 0.985, 10),
    gold: round(ms * 1.05, 100),
    silver: round(ms * 1.17, 100),
    bronze: round(ms * 1.35, 100),
  };
  console.log(def.id.padEnd(18), (best).toFixed(2) + 's', JSON.stringify(out[def.id]));
}
const body = `// Medal times in ms per track. Generated by \`node tools/medals.mjs\` from AI runs:
// author is just under the best bot lap; gold/silver/bronze are +5% / +17% / +35%.
export const MEDALS = ${JSON.stringify(out, null, 2).replace(/"(\w[\w-]*)":/g, (m, k) => (/^[a-z]\w*$/.test(k) ? `${k}:` : `'${k}':`))};
`;
writeFileSync(join(root, 'src/track/medals.js'), body);
console.log('wrote src/track/medals.js');
